### ISSUE TITLE
Fixed division test case for Calculator.js

### ISSUE THREAD

**Issue by usaketh** [100xdevs-cohort-2/assignments#108]
JavaScript doesn't throw a regular error for division by zero, and instead returns Infinity or -Infinity, we need to adjust the test accordingly.

In this modification, the test checks if the result of the division by zero is equal to Infinity. This aligns with the behavior of JavaScript when dividing a number by zero.

**Comment by shashanksingh2002** [comment]
Then you should generate a customer error message using `throw new Error('Error message')`

**Comment by V2K4Y** [comment]
Try to handle in your own way, there are different methods to tackle this.

**Comment by usaketh** [comment]
done
