### ISSUE TITLE
week 10 test folder showing missing types, can't even run anything, nor can't compile the ts files into js files

### ISSUE THREAD

**Issue by async-avi** [100xdevs-cohort-2/assignments#822]
![PROB](https://github.com/100xdevs-cohort-2/assignments/assets/151649503/688e6c9c-201e-4cec-987d-584411d660a3)

**Comment by RushikeshShelar** [comment]
There is only one problem that gives the following error - 
`Parameter 'todo' implicitly has an 'any' type` to resolve this follow the below steps:
1. Go in `tsconfig.json`
2. Add the following line under Complier Options in `tsconfig.json`
```shell
"noImplicitAny": false
```
3. Save the file.

**Comment by thearpitsarap** [comment]
![image](https://github.com/100xdevs-cohort-2/assignments/assets/73021176/927265e2-7b9a-4273-b0b7-d604f84d4496)

Added, but still facing same issue

![image](https://github.com/100xdevs-cohort-2/assignments/assets/73021176/e36c6a3b-9ef0-45db-bac1-0bb5b289da7b)

**Comment by Rajgupta36** [comment]
same issue
