### ISSUE TITLE
Issue while setting up in Windows.

### ISSUE THREAD

**Issue by n07kiran** [100xdevs-cohort-2/assignments#894]
`package.json` file is missing! 
when I ran `npm install` command from the `'assignments-master'` directory, 
it showed error, that's related to missing `package.json.`
<img width="501" alt="image" src="https://github.com/100xdevs-cohort-2/assignments/assets/90110992/dd290551-d6a1-4902-b256-6fa3fedbca60">

I have tried the following in `assignmensts-master/01-js` directory and got these errors!
<img width="697" alt="image" src="https://github.com/100xdevs-cohort-2/assignments/assets/90110992/0a30952b-eb3d-4d44-afd9-b56f78ed75cd">

**Comment by mig9mili** [comment]
///this is because \Roaming\npm  file or directory is not present   so  Manually create that  
 
1. go to the command prompt
2. cd AppData
3 mkdir Roaming\npm

// done

//then go to vscode  try to run 

it may ask for "jest"  installation press Y

**Comment by PranshuRaj1** [comment]
@mig9mili can you explain more clearly?
I think there should be package.json file which should be provided.

**Comment by mig9mili** [comment]
true @PranshuRaj1 , but that  assignments-master/01-js  already has package.json,   if that not a problem than we have to check whether that path exits or not  to install their dependence

**Comment by IamRitz** [comment]
> true @PranshuRaj1 , but that assignments-master/01-js already has package.json, if that not a problem than we have to check whether that path exits or not to install their dependence

we can recursively install those packages, below is how I did it (requires administrative privileges on my system)

`sudo npm i -g recursive-install`

**Comment by n07kiran** [comment]
> ///this is because \Roaming\npm file or directory is not present so Manually create that
> 
> 1. go to the command prompt
> 2. cd AppData
>    3 mkdir Roaming\npm
> 
> // done
> 
> //then go to vscode try to run
> 
> it may ask for "jest" installation press Y


Thank you @mig9mili  !! it worked!
